# Generated by Django 2.1.7 on 2019-02-18 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spec',
            name='projecte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projecte'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sprint'),
        ),
    ]
